# SPDX-FileCopyrightText: 2024 The Simplified Coding Team <main@simplifiedcoding.org>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "Simplified Coding"
SPDX-PackageSupplier = "The Simplified Coding Team <main@simplifiedcoding.org>"
SPDX-PackageDownloadLocation = "simplifiedcoding.org"
annotations = []
